name: 2.Request to change information
description: Select this if you would like to request an change to your information
labels: ["Change information"]
assignees:
  - RealLanta
body:
  - type: markdown
    attributes:
      value: |
        Please write "your website name" in the title!
  - type: input
    id: name
    attributes:
      label: The old subdomain
      description: Please write your old subdomain
      placeholder: ex. xxx.archlinux.cyou
    validations:
      required: true
  - type: input
    id: name
    attributes:
      label: The website name
      description: will show it in README.md
      placeholder: ex. My blog
    validations:
      required: true
  - type: input
    id: subdomain
    attributes:
      label: What do you want your new subdomain prefix to be?
      description: |
        such as xxx.archlinux.cyou
      placeholder: ex. xxx.archlinux.cyou
    validations:
      required: true
  - type: input
    id: resolution-type
    attributes:
      label: Resolution type
      description: |
        Support A,AAAA,CNAME
      placeholder: ex. A
    validations:
      required: true
  - type: input
    id: resolution-content
    attributes:
      label: Resolution content
      description: |
        Support IP or domains
      placeholder: ex. 1.1.1.1
    validations:
      required: true
